name: Test

on:
  pull_request:
  push:
    branches: [ master, main, develop ]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
          configFilePath: ./gitversion.yml
      - name: Display SemVer
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: DamianReeves/write-file-action@master
        with:
          path: .version
          write-mode: overwrite
          contents: ${{ needs.version.outputs.version }}
      - uses: ./
        with:
          input-directory: test